import { FormEvent, useRef, useState } from 'react'
import { Eye, EyeOff, KeyRound, Mail, ShieldCheck } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { activateDemoDb, activateMainDb } from '../../lib/db'
import { seedDemoData } from '../../lib/demo-data'
import { documentClient } from '../../lib/document-client'
import { resetUserPassword, signInGoogle, signInUser, signUpUser } from '../../lib/user-auth'
import { createSingleFlight } from '../../lib/oauth-login'
import { useAuthStore } from '../stores/authStore'

export default function Login() {
  const client=documentClient(); const navigate=useNavigate()
  const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[googleBusy,setGoogleBusy]=useState(false),[message,setMessage]=useState(''),[sent,setSent]=useState(false)
  const runGoogle = useRef(createSingleFlight()).current
  const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('');setSent(false);try{activateMainDb();if(!client)throw new Error('Login cloud belum dikonfigurasi. Gunakan Mode Demo atau isi pengaturan Supabase.');if(register){if(password.length<8)throw new Error('Kata sandi minimal 8 karakter.');const session=await signUpUser(client,email,password);if(session)navigate('/');else setSent(true)}else{await signInUser(client,email,password);navigate('/')}}catch(error){setMessage(error instanceof Error?error.message:'Login belum berhasil.')}finally{setBusy(false)}}
  const google=()=>runGoogle(async()=>{if(!client){setMessage('Login Google belum dikonfigurasi.');return}setBusy(true);setGoogleBusy(true);setMessage('');try{activateMainDb();await signInGoogle(client)}catch(error){setMessage(error instanceof Error?error.message:'Login Google belum berhasil.')}finally{setBusy(false);setGoogleBusy(false)}})
  const reset=async()=>{if(!client||!email.trim()){setMessage('Isi email terlebih dahulu untuk menerima tautan reset.');return}setBusy(true);setMessage('');try{await resetUserPassword(client,email);setSent(true)}catch(error){setMessage(error instanceof Error?error.message:'Tautan reset belum berhasil dikirim.')}finally{setBusy(false)}}
  const demo=async()=>{setBusy(true);setMessage('');try{activateDemoDb();await seedDemoData();useAuthStore.getState().setDemo();navigate('/')}catch{setMessage('Mode Demo belum berhasil dibuka. Coba lagi.')}finally{setBusy(false)}}
  return <main className="grid min-h-dvh place-items-center bg-slate-100 px-4 py-6"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-5 shadow-xl sm:p-7"><div className="text-center"><img src="/icons/logo-bgy.webp" alt="Logo BGY Wali Kelas" className="mx-auto size-16 rounded-2xl object-contain"/><h1 className="mt-4 text-2xl font-black text-slate-900">BGY Wali Kelas</h1><p className="mt-1 text-sm leading-5 text-slate-600">{register?'Buat akun guru baru.':'Masuk untuk melanjutkan ke kelasmu.'}</p></div>
    {message&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</p>}{sent&&<p role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">Periksa emailmu untuk melanjutkan.</p>}
    <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-bold text-slate-700"><span className="flex items-center gap-2"><Mail size={16}/>Email</span><input name="email" required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="field mt-2" placeholder="guru@sekolah.sch.id"/></label><label className="block text-sm font-bold text-slate-700"><span className="flex items-center justify-between"><span className="flex items-center gap-2"><KeyRound size={16}/>Kata sandi</span>{!register&&<button type="button" onClick={reset} className="font-semibold text-teal-700 hover:underline">Lupa kata sandi?</button>}</span><span className="relative mt-2 block"><input name="password" required type={showPassword?'text':'password'} minLength={8} autoComplete={register?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} className="field w-full pr-12" placeholder="Minimal 8 karakter"/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="absolute inset-y-0 right-0 grid w-12 place-items-center text-slate-500" aria-label={showPassword?'Sembunyikan kata sandi':'Tampilkan kata sandi'}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label><button disabled={busy||!client} className="action-primary min-h-12 w-full rounded-xl px-4 font-bold hover:brightness-105 disabled:opacity-40">{busy?'Memproses…':register?'Buat akun':'Masuk'}</button></form>
    <div className="my-5 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>atau masuk dengan<span className="h-px flex-1 bg-slate-200"/></div>
    <button type="button" disabled={busy||!client} onClick={google} className="flex min-h-12 w-full items-center justify-center gap-3 rounded-xl border border-slate-300 bg-white px-4 font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-40"><span className="text-lg font-black">G</span>{googleBusy?'Membuka Google…':'Lanjutkan dengan Google'}</button>
    <p className="mt-5 text-center text-sm text-slate-600">{register?'Sudah punya akun?':'Belum punya akun?'} <button type="button" onClick={()=>{setRegister(v=>!v);setMessage('');setSent(false)}} className="font-bold text-teal-700 hover:underline">{register?'Masuk':'Buat akun'}</button></p>
    <div className="mt-5 border-t border-slate-100 pt-5 text-center"><button type="button" disabled={busy} onClick={demo} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-bold text-slate-600 hover:bg-slate-50 disabled:opacity-40"><ShieldCheck size={17}/>Coba Mode Demo</button><p className="mt-1 text-xs text-slate-500">Tanpa akun, untuk mencoba aplikasi.</p></div>
  </section></main>
}
